export const testTweets = [
  {
    id: 1,
    user: "Achintya Pandey",
    handle: "@achintya453",
    text: "Just built my first mini Twitter clone using React 🚀 Feeling proud!",
    image: "https://picsum.photos/id/0/600/400",
    likes: 124,
    comments: 12,
    reposts: 5,
    time: "2h"
  },
  {
    id: 2,
    user: "CodeWithRaj",
    handle: "@coder_raj",
    text: "Debugging code at 2AM hits different 😴💻 Check out this peaceful video.",
    video: "https://assets.mixkit.co/videos/preview/mixkit-typing-on-a-backlit-computer-keyboard-at-night-4417-large.mp4",
    likes: 89,
    comments: 7,
    reposts: 3,
    time: "4h"
  },
  {
    id: 3,
    user: "DevGirl",
    handle: "@devgirl99",
    text: "CSS is easy until it's not 😭 #frontend",
    image: "https://picsum.photos/id/20/600/400",
    likes: 342,
    comments: 28,
    reposts: 15,
    time: "6h"
  },
  {
    id: 4,
    user: "TechMemer",
    handle: "@404brain",
    text: "My code works. I have no idea why. My code breaks. I have no idea why.",
    image: "https://picsum.photos/id/26/600/400",
    likes: 567,
    comments: 45,
    reposts: 23,
    time: "8h"
  },
  {
    id: 5,
    user: "Startup Guy",
    handle: "@buildinpublic",
    text: "Day 15 of building in public: still no users but learning a LOT 🔥",
    image: "https://picsum.photos/id/91/600/400",
    likes: 234,
    comments: 18,
    reposts: 9,
    time: "12h"
  },
  {
    id: 6,
    user: "AI Enthusiast",
    handle: "@ai_future",
    text: "AI is not replacing developers, it's upgrading them.",
    image: "https://picsum.photos/id/1/600/400",
    likes: 891,
    comments: 67,
    reposts: 34,
    time: "14h"
  },
  {
    id: 7,
    user: "Fitness Freak",
    handle: "@fitdev",
    text: "Code. Gym. Repeat. 💪",
    video: "https://assets.mixkit.co/videos/preview/mixkit-man-doing-push-ups-in-a-sunny-gym-4416-large.mp4",
    likes: 156,
    comments: 11,
    reposts: 6,
    time: "1d"
  },
  {
    id: 8,
    user: "Sarcastic Dev",
    handle: "@bug_creator",
    text: "99 little bugs in the code, take one down patch it around… 127 bugs in the code 😂",
    image: "https://picsum.photos/id/15/600/400",
    likes: 723,
    comments: 52,
    reposts: 28,
    time: "1d"
  },
  {
    id: 9,
    user: "Night Owl",
    handle: "@latenightdev",
    text: "Best ideas come after midnight 🌙",
    image: "https://picsum.photos/id/22/600/400",
    likes: 445,
    comments: 31,
    reposts: 12,
    time: "2d"
  },
  {
    id: 10,
    user: "Frontend Master",
    handle: "@uiwizard",
    text: "Spent 3 hours fixing alignment… turned out to be margin 😑",
    image: "https://picsum.photos/id/30/600/400",
    likes: 678,
    comments: 41,
    reposts: 19,
    time: "2d"
  },
  {
    id: 11,
    user: "JS Ninja",
    handle: "@jsninja",
    text: "Understanding closures finally feels like unlocking a superpower ⚡",
    video: "https://assets.mixkit.co/videos/preview/mixkit-set-of-abstract-digital-data-3404-large.mp4",
    likes: 512,
    comments: 38,
    reposts: 21,
    time: "3d"
  },
  {
    id: 12,
    user: "Coffee Dev",
    handle: "@caffeinecoder",
    text: "Coffee ☕ + Code 💻 = Productivity 🚀",
    image: "https://picsum.photos/id/36/600/400",
    likes: 902,
    comments: 73,
    reposts: 42,
    time: "3d"
  },
  {
    id: 13,
    user: "Backend Bro",
    handle: "@server_side",
    text: "Frontend gets the glory, backend does the real work 😎",
    image: "https://picsum.photos/id/42/600/400",
    likes: 345,
    comments: 28,
    reposts: 14,
    time: "4d"
  },
  {
    id: 14,
    user: "UI Designer",
    handle: "@pixelperfect",
    text: "Good UI is invisible. Bad UI is unforgettable.",
    image: "https://picsum.photos/id/48/600/400",
    likes: 567,
    comments: 42,
    reposts: 19,
    time: "5d"
  },
  {
    id: 15,
    user: "Git Master",
    handle: "@commitpush",
    text: "git commit -m 'final fix' 🤡",
    image: "https://picsum.photos/id/60/600/400",
    likes: 789,
    comments: 56,
    reposts: 31,
    time: "6d"
  },
  {
    id: 16,
    user: "StackOverflow Fan",
    handle: "@copy_paste_dev",
    text: "If StackOverflow goes down, I go down.",
    image: "https://picsum.photos/id/76/600/400",
    likes: 432,
    comments: 34,
    reposts: 12,
    time: "1w"
  },
  {
    id: 17,
    user: "React Dev",
    handle: "@useEffect_king",
    text: "Why is useEffect running twice?? 😭",
    video: "https://assets.mixkit.co/videos/preview/mixkit-animation-of-futuristic-circuits-9141-large.mp4",
    likes: 654,
    comments: 48,
    reposts: 23,
    time: "1w"
  },
  {
    id: 18,
    user: "Cyber Dude",
    handle: "@securecode",
    text: "Security is not a feature, it's a necessity 🔐",
    image: "https://picsum.photos/id/0/600/400",
    likes: 321,
    comments: 19,
    reposts: 8,
    time: "1w"
  }
];