export const testTweets = [
    {
    id: 1,
    user: "Achintya Pandey",
    handle: "@achintya453",
    text: "Just built my first mini Twitter clone using React 🚀 Feeling proud!",
  },
  {
    id: 2,
    user: "CodeWithRaj",
    handle: "@coder_raj",
    text: "Debugging code at 2AM hits different 😴💻",
  },
  {
    id: 3,
    user: "DevGirl",
    handle: "@devgirl99",
    text: "CSS is easy until it’s not 😭 #frontend",
  },
  {
    id: 4,
    user: "TechMemer",
    handle: "@404brain",
    text: "My code works. I have no idea why. My code breaks. I have no idea why.",
  },
  {
    id: 5,
    user: "Startup Guy",
    handle: "@buildinpublic",
    text: "Day 15 of building in public: still no users but learning a LOT 🔥",
  },
  {
    id: 6,
    user: "AI Enthusiast",
    handle: "@ai_future",
    text: "AI is not replacing developers, it’s upgrading them.",
  },
  {
    id: 7,
    user: "Fitness Freak",
    handle: "@fitdev",
    text: "Code. Gym. Repeat. 💪",
  },
  {
    id: 8,
    user: "Sarcastic Dev",
    handle: "@bug_creator",
    text: "99 little bugs in the code, take one down patch it around… 127 bugs in the code 😂",
  },
  {
    id: 9,
    user: "Night Owl",
    handle: "@latenightdev",
    text: "Best ideas come after midnight 🌙",
  },
  {
    id: 10,
    user: "Frontend Master",
    handle: "@uiwizard",
    text: "Spent 3 hours fixing alignment… turned out to be margin 😑",
  },
  
  {
    id: 11,
    user: "JS Ninja",
    handle: "@jsninja",
    text: "Understanding closures finally feels like unlocking a superpower ⚡",
  },
  {
    id: 12,
    user: "Bug Hunter",
    handle: "@fixingbugs",
    text: "Spent 5 hours debugging… it was a missing semicolon.",
  },
  {
    id: 13,
    user: "Coffee Dev",
    handle: "@caffeinecoder",
    text: "Coffee ☕ + Code 💻 = Productivity 🚀",
  },
  {
    id: 14,
    user: "Backend Bro",
    handle: "@server_side",
    text: "Frontend gets the glory, backend does the real work 😎",
  },
  {
    id: 15,
    user: "UI Designer",
    handle: "@pixelperfect",
    text: "Good UI is invisible. Bad UI is unforgettable.",
  },
  {
    id: 16,
    user: "Lazy Coder",
    handle: "@procrasticode",
    text: "I’ll fix this bug tomorrow… maybe.",
  },
  {
    id: 17,
    user: "Git Master",
    handle: "@commitpush",
    text: "git commit -m 'final fix' 🤡",
  },
  {
    id: 18,
    user: "StackOverflow Fan",
    handle: "@copy_paste_dev",
    text: "If StackOverflow goes down, I go down.",
  },
  {
    id: 19,
    user: "React Dev",
    handle: "@useEffect_king",
    text: "Why is useEffect running twice?? 😭",
  },
  {
    id: 20,
    user: "Cyber Dude",
    handle: "@securecode",
    text: "Security is not a feature, it’s a necessity 🔐",
  },
  {
    id: 21,
    user: "Optimistic Dev",
    handle: "@hopefulcoder",
    text: "This time it will work… I believe 🙏",
  },
  {
    id: 22,
    user: "Tech News",
    handle: "@dailytech",
    text: "AI tools are changing the way we build products every day.",
  },
  {
    id: 23,
    user: "Freelancer",
    handle: "@indiedev",
    text: "Client: small change. The change: rebuild entire app.",
  },
  {
    id: 24,
    user: "College Coder",
    handle: "@studentdev",
    text: "Assignment due tomorrow, learning everything today 😅",
  },
  {
    id: 25,
    user: "Debug Queen",
    handle: "@consolelog",
    text: "console.log is still my best friend ❤️",
  },
  {
    id: 26,
    user: "Mobile Dev",
    handle: "@appbuilder",
    text: "Building apps that people actually use feels amazing 📱",
  },
  {
    id: 27,
    user: "Minimalist",
    handle: "@lessismore",
    text: "Clean code > clever code.",
  },
  {
    id: 28,
    user: "Hacker Mindset",
    handle: "@thinkdifferent",
    text: "There’s always a smarter way to solve a problem.",
  },
  {
    id: 29,
    user: "Weekend Dev",
    handle: "@sideproject",
    text: "Weekends are for side projects 🚀",
  },
  {
    id: 30,
    user: "Motivation Hub",
    handle: "@keepcoding",
    text: "Consistency beats talent. Keep coding 💯",
  }
];
